### ISSUE TITLE
Missing website

### ISSUE THREAD

**Issue by zdroid** [FRBNY-DSGE/DSGE.jl#101]
This repository is missing a website link in its description. Reasons to do this are listed in [this Discourse thread](https://discourse.julialang.org/t/a-suggestion-for-package-maintainers/44111).

https://frbny-dsge.github.io/DSGE.jl/latest/ is an example of a good link for this purpose.

**Comment by chenwilliam77** [comment]
Thanks for the heads up, README has been updated.

**Comment by zdroid** [comment]
@chenwilliam77 I meant it should be there:
![Annotation 2020-08-12 121154](https://user-images.githubusercontent.com/2725611/90003899-0e842300-dc95-11ea-9c11-1f522ff5e086.png)

**Comment by chenwilliam77** [comment]
My bad, thanks for the clarification.
