### ISSUE TITLE
Getting "Killed" message after forecasting completes

### ISSUE THREAD

**Issue by aharmsen** [FRBNY-DSGE/DSGE.jl#108]
I'm running the Model1010("ss20") model with all defaults, and loading in FRED data dynamically. The whole system seems to run without any issues, and then when it gets to 2500 of 2500 blocks in the forecasting step, the program exits with a "Killed" message and no more information. The OS is Ubuntu 20.04, and I have about 10GB RAM allocated to this virtual machine.

See image attached:
![image](https://user-images.githubusercontent.com/3521986/95692331-e1db8180-0bd9-11eb-8a8e-6a5efa953a3d.png)

Any idea what might be going on?

**Comment by ShlokG** [comment]
This is likely a memory kill message that occurs after the code finishes forecasting. Try running a forecast on fewer particles (say 100) and lower the forecast_jstep and forecast_block_size to 1 and 10 respectively. The code will look like this (including initializing the model):

`m = Model1010("ss20")
m <= Setting(:forecast_jstep, 1)
m <= Setting(:forecast_block_size,10)
m <= Setting(:n_particles, 100)`

Let me know if that doesn't help.

**Comment by aharmsen** [comment]
this fixed the problem, thank you very much for your help!
