### ISSUE TITLE
solve_hjb() and solve_kfe()

### ISSUE THREAD

**Issue by azev77** [FRBNY-DSGE/DSGE.jl#110]
Hi and thank you for this package. 

Is it possible to provide simple examples of how to use [solve_hjb](https://github.com/FRBNY-DSGE/DSGE.jl/blob/master/src/models/heterogeneous/solve_hjb.jl)() and [solve_kfe](https://github.com/FRBNY-DSGE/DSGE.jl/blob/master/src/models/heterogeneous/solve_kfe.jl)()>

The code is similar to Ben Moll's, so perhaps minimal examples like: 
[Lifecycle](https://benjaminmoll.com/wp-content/uploads/2020/06/lifecycle.m) ([note](https://benjaminmoll.com/wp-content/uploads/2020/06/lifecycle.pdf))
[Huggett_diffusion](https://benjaminmoll.com/wp-content/uploads/2020/06/HJB_diffusion_implicit.m)
[Huggett_diffusion_pe](https://benjaminmoll.com/wp-content/uploads/2020/06/huggett_diffusion_partialeq.m)
[Aiyagai_diffusion](https://benjaminmoll.com/wp-content/uploads/2020/06/aiyagari_diffusion_equilibrium.m) ([Julia version](https://benjaminmoll.com/wp-content/uploads/2020/06/aiyagari_diffusion_equilibrium.jl.txt))
[Aiyagari_diffusion_transition](https://benjaminmoll.com/wp-content/uploads/2020/06/aiyagari_diffusion_transition.m)
[RBC_diffusion](https://benjaminmoll.com/wp-content/uploads/2020/06/HJB_diffusion_implicit_RBC.m)

**Comment by chenwilliam77** [comment]
Hi azev77,

We haven't worked on continuous-time methods in a while, and we are currently busy with other projects. As a result, it is unlikely in the near term that we can provide as many examples as Ben Moll has.

However, we do have a [continuous-time implementation of Krusell Smith](https://github.com/FRBNY-DSGE/DSGE.jl/blob/master/src/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl) that uses `solve_hjb` and `solve_kfe`. Note though that these two functions are not "exhaustive" approaches for solving the HJB and KFE, and depending on the nature of the problem at hand, you may need to use a different numerical approach.

**Comment by azev77** [comment]
@chenwilliam77, thanks for your response. 
1.  The continuous-time Krusell Smith example in tests gives an error. 
[test/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl](test/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl)
```julia
julia> m = KrusellSmithCT()
ERROR: UndefVarError: SteadyStateParameterArray not defined
```
2. Ofcourse I don't expect as many examples as Moll's website. 
I mean one very simple, working example such [lifecycle](https://benjaminmoll.com/wp-content/uploads/2020/06/lifecycle.m)...

**Comment by chenwilliam77** [comment]
This is our bad; we forgot to update the name of a type from one of our other packages [ModelConstructors.jl](https://github.com/FRBNY-DSGE/ModelConstructors.jl). If you switch every instance of `SteadyStateParameterArray` to `SteadyStateParameterGrid` in [src/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl](https://github.com/FRBNY-DSGE/DSGE.jl/blob/master/src/models/heterogeneous/krusell_smith_ct/krusell_smith_ct.jl) (there should only be a few), then the model should be instantiate correctly. I've made this fix on a dev branch, but there are other extant changes that have been made to that branch which cannot be merged just yet into the main package, so I can't just make a new release with this bug fix at the moment.

FYI, the test script appears to use other deprecated functions from ModelConstructors.jl, so you should test the model works by simply calling in REPL
```
using DSGE
m = KrusellSmithCT()
```
During instantiation, the steady state should be solved.

If you also want to linearize, then you'll need to add `using ForwardDiff, BasisMatrices` to the src/DSGE.jl script. Unfortunately, it looks like the developers on DSGE.jl who implemented KrusellSmithCT didn't fully implement the linearization code and thus forgot to add these two dependencies. Running
```
T, R, C = solve(m)
```
will deliver the linearization, where
```
ds_t = (T * s_t) * dt + R * dW_t + C
```

Let me know if this works, and I can close the issue if it does.
