### ISSUE TITLE
metropolis-hastings draws fixed at the mode for some free parameters

### ISSUE THREAD

**Issue by giorgiomas** [FRBNY-DSGE/DSGE.jl#118]
Hi,

I'm experiencing some problems when I try to implement the metropolis-hastings step in estimation.
Even though I'm able to get the mhsave output with the entire posterior distribution, the draws on some **free** parameters are all fixed at the mode, as if the mh step was not carried out at all on some of them.
I've been working on a variant of the m1010 model, but I tried with other specifications, also SmetsWouters, and got into the same issue.

Looking at the code, it seems to me that instead of referencing the _n_ free parameters, the mh step is run for the first _n_ parameters as they are sorted in the model file (where _n_ is the number of free parameters); the remaining parameters, i.e. after the first _n_, are left at the mode, as if they were fixed.

I refer to line 101 of the metropolis_hastings.jl file:
`blocks_all     = SMC.generate_param_blocks(n_free_para, n_param_blocks)`
Notwithstanding the number of parameters blocks, the SMC function takes just the **number** of free parameters, and not their indexes. Then, the mh step is run with a loop on this `blocks_all` at line 132:
`for (k, block_a) in enumerate(blocks_all)`
so that draws are taken only for parameters whose index goes from 1 to _n_ (at least to my understanding).

I'd like to know if my guess is correct, or if I'm missing something.

Btw, thank you for the great package!

**Comment by chenwilliam77** [comment]
Hi giorgiomas,

Thank you for catching this bug. Unless you want to submit a pull request, I will try to fix this error next week and let you know what I did to fix it since I don't anticipate a new release will be available until at least a month from now.

Best,

William

**Comment by giorgiomas** [comment]
Hi William,

thank you for the prompt answer! Actually, I'm quite new to Julia, so I don't think I'm going to submit a pull request. I mean, I've already written another function in place of `generate_param_blocks` that works, but I'm pretty sure that there are better ways than how I did it, codewise speaking.
I just meant to be sure I was not wrong, and to let you know in case.

Thank you anyway,

Giorgio

**Comment by chenwilliam77** [comment]
Here's the fix I used:

Instead of 
```
free_para_inds = findall([!θ.fixed for θ in parameters])
n_free_para    = length(free_para_inds)
n_params       = length(parameters)
blocks_all     = SMC.generate_param_blocks(n_free_para, n_param_blocks)
```

a fix would be
```
free_para_inds = findall([!θ.fixed for θ in parameters])
n_params       = length(parameters)
if n_param_blocks == 1
    blocks_all = Vector{Int}[free_para_inds]
else
    n_free_para    = length(free_para_inds)
    blocks_all      = SMC.generate_free_blocks(n_free_para, n_param_blocks)
    for block_a in blocks_all
        sort!(block_a)
    end
end
```

**Comment by giorgiomas** [comment]
Thanks!
