### ISSUE TITLE
Eval can be replaced by getfield in smooth

### ISSUE THREAD

**Issue by julbinb** [FRBNY-DSGE/DSGE.jl#120]
`getfield` would be more efficient than `eval` in getting the value of a variable/function name here:

https://github.com/FRBNY-DSGE/DSGE.jl/blob/e55b4dc2222d062d968a1ee75f4d76b0a91eb8a3/src/forecast/smooth.jl#L78

Toy example:

```julia
julia> using BenchmarkTools

julia> foo = 42
42

julia> @btime eval(Symbol("foo"))
  44.230 ns (0 allocations: 0 bytes)
42

julia> @btime getfield(Main, Symbol("foo"))
  1.180 ns (0 allocations: 0 bytes)
42
```

**Comment by chenwilliam77** [comment]
Thanks for this! This change will be added to the next release of the package.
