### ISSUE TITLE
ZLB handling method

### ISSUE THREAD

**Issue by giorgiomas** [FRBNY-DSGE/DSGE.jl#146]
Hi and thank you for this great package,

I would like to ask a clarification question on one method of handling the ZLB, in particular, the "second way" mentioned [here](https://frbny-dsge.github.io/DSGE.jl/latest/advanced_usage/#Handling-of-the-Zero-Lower-Bound-(ZLB)-1).

Does the split in two regimes "only" serve to set the standard deviation of anticipated policy shocks to zero in the pre-ZLB period (as apparent in [this section](https://github.com/FRBNY-DSGE/DSGE.jl/blob/main/src/estimate/kalman.jl#L273) of the code), or is there a more complex approach or filtering procedure?
Dynare is about to introduce a "heteroskedastic filter and smoother" (see [here](https://git.dynare.org/Dynare/dynare/-/commit/1645f38269e445e6a686a6889420012106794985)) that allows fixing the standard deviation of a given shock to 0 in a specified period. I was wondering if the idea behind this tool is in line with the approach implemented in Julia for the FRBNY model.

I realize this is more of a question than an issue, and I apologize for that. Still, I hope that a comparison between methodologies used in Julia and Dynare can turn out to be useful to other users.

Thanks,
Giorgio

**Comment by ShlokG** [comment]
Hi Giorgio,

Thanks for your question (and for the helpful links)!

You are correct that the split in two regimes only sets the standard deviation of anticipated policy shocks to zero in the pre-ZLB period. Our filtering and smoothing procedures allow for different matrices at each time period (in this case, only the QQ matrix changes). We make extensive use of that in the "first way" in the link you provided.

Our filtering and smoothing code are in a separate package called StateSpaceRoutines.jl. You can see that a vector of the matrices can be provided, with the matrices changing over time in [filtering](https://github.com/FRBNY-DSGE/StateSpaceRoutines.jl/blob/main/src/filters/kalman_filter.jl) and [smoothing](https://github.com/FRBNY-DSGE/StateSpaceRoutines.jl/blob/main/src/smoothers/koopman_smoother.jl).

The approach behind this appears to be identical between this package and the method in Dynare. My understanding from the brief look I took in the Dynare code is that Dynare only allows the Q matrix to change over time whereas this package allows all the matrices to do so. For the implementation of heteroskedasticity, though, I believe they are the same.

Let me know if that doesn't answer your question and I would be happy to provide more details.

Regards,
Shlok

**Comment by giorgiomas** [comment]
Hi Shlok,

Thank you for your feedback and for redirecting me to the StateSpaceRoutines.jl codes!
Your explanation definitely clarifies my doubts and answers my question.

Cheers,
Giorgio
