### ISSUE TITLE
Tags in METADATA?

### ISSUE THREAD

**Issue by pkofod** [FRBNY-DSGE/DSGE.jl#15]
I'm sort of confused about the versioning and the registration in METADATA. I see you have a v0.4 tagged, but 0.1.4 seems like the newest in METADATA? https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/DSGE Am I missing something?

**Comment by abhig94** [comment]
Metadata now reflects the full sequence of tagged releases from 0.1.4 through 0.4.0, so this is resolved.
