### ISSUE TITLE
UndefVarError: Optimizer not defined

### ISSUE THREAD

**Issue by heqiang1122** [FRBNY-DSGE/DSGE.jl#16]
I run this DSGE.jl in Julia,and get "WARNING: could not import Optim.Optimizer into DSGE. ERROR: LoadError: LoadError: LoadError: UndefVarError: Optimizer not defined
".Could you help me to solve this problem, please?

**Comment by pearlzli** [comment]
This should be fixed in 0ea9ceb6980c36d0d7736f09895d1ae52454c358. Run `Pkg.checkout("DSGE")` to pull the latest version of the master branch. Thanks for pointing this out!
