### ISSUE TITLE
Installation hangs with Julia 1.6.3

### ISSUE THREAD

**Issue by danmrc** [FRBNY-DSGE/DSGE.jl#160]
Hello,

I am using Julia 1.6.3 on arch linux. I am using the aur version due to issues with llvm. I tried `]` and `add DSGE` but it hangs in the **Resolving package versions...**. It clearly is doing something, because the network is using 5mbs of download. I can install any other package and I can install the 1.1.6 version using `add DSGE@1.1.6`. 

I am not sure what is the problem (if there is one), but maybe the readme should be more clear about this?

I will be glad to help you with more information

Thanks in advance

**Comment by ShlokG** [comment]
Hi Daniel,

Thanks for your message and sorry for my delayed response. We haven't tested DSGE on 1.6 yet. We have currently only tested on Julia version <= 1.5 (I realize the Project.toml is misleading then and is something I will fix now). The issue you are facing is likely that we have not updated our package compatibilities in a while and so Julia is unable to resolve compatibility versions in 1.6 (eg. the package version we require are not supported in 1.6). 

We are very busy until February and are planning to test and upgrade all our dependency versions then. Sorry for the delay! I will post a message here when it's been done. In the meantime, you shouldn't have issues using our package in 1.5.

Regards,
Shlok

**Comment by danmrc** [comment]
Hello,

I've tried to install the package recently and it works without problems.

Thank you very much

Daniel Coutinho
