### ISSUE TITLE
make_packet.jl

### ISSUE THREAD

**Issue by breussf** [FRBNY-DSGE/DSGE.jl#168]
Dear Shlok,

(1)	The run with „run_default.jl” (m = SmetsWouters() model) was successful with Julia version 1.1.1. The results were saved as “tex” files in:
C:/.julia/packages/DSGE/fjU1P/save/output_data/smets_wouters/ss0/estimate/tables/…*.tex (4 files for Tabl1: moments, parameter estimates etc….)

               After the input: “ENV[“FRED_API_KEY”] = “[my key]”
(2)	The run with “make_packet.jl” (m = SmetsWouters() model) was not successful and delivered the following error messages:

“Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded”  --- this line is repeated several times

After telling that the “dataset creation successful” – obs_gdp, Frequency of missing/NaNs: 0.0” … this statement for other variables, e.g.: “obs_hours, Frequency of missing/NaNs: 0.07594…”

“Info: Forecasting block 1 of 50… “

Loading draws from c:\users\fritz\OneDrive\Dokumente\GitHub\DSGE.jl\examples/../test/reference/mhsave_vint=181115.h5
ERROR: LoadError: New value of ρ_μ (-45.498892312835) is out of bounds ((1.0e-5, 0.999))

Then the run stops and refers to the file “make_packet.jl” – line 60.

Why is it not possible to replicate the file “make_packet.jl” when all inputs/changes (e.g. m = SmetsWouters()) are made correctly?

Best regards,
Fritz

**Comment by ShlokG** [comment]
This is the same issues as in https://github.com/FRBNY-DSGE/DSGE.jl/issues/167.
