### ISSUE TITLE
run_default.jl

### ISSUE THREAD

**Issue by breussf** [FRBNY-DSGE/DSGE.jl#171]
Dear Shlok,

thank you for the hint to change the loading filepath to capture the Smets_Wouters “.h5” file. I did this by changing line 55:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#      overrides[:full] = "$(fn)/../test/reference/mhsave_vint=181115.h5"
overrides[:full] = "c:/users/fritz/.julia/packages/DSGE/fjU1P/save/output_data/smets_wouters/ss0/estimate/raw/mhsave_vint=181115.h5"
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Maybe this was not the correct statement of the new filepath, because I got the following error messages:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[ Info: Forecasting block 1 of 50...
Loading draws from c:/users/fritz/.julia/packages/DSGE/fjU1P/save/output_data/smets_wouters/ss0/estimate/raw/mhsave_vint=181115.h5
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5Pdcpl.c line 2048 in H5Pset_chunk(): all chunk dimensions must be positive
    major: Invalid arguments to routine
    minor: Out of range
ERROR: LoadError: Error setting chunk size
Stacktrace:
[1] error(::String) at .\error.jl:33
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Did I change line 55 not correctly?

Best regards,
Fritz

**Comment by danielrjohn** [comment]
Remove all mentions of pseudo variables in the makepacket file, e.g. "forecastpseudo". The Smets Wouters model doesn't define any pseudo-observables, so calling them in the makepacket file causes an error because these matrices are zero, which they are not allowed to be when calling them ("chunk dimensions must be positive").
