### ISSUE TITLE
Can't Get Simple Example To Xqt

### ISSUE THREAD

**Issue by MOAMaster** [FRBNY-DSGE/DSGE.jl#177]
I created a file with the sample program from https://frbny-dsge.github.io/DSGE.jl/stable/running_existing_model/
and added the necessary using statement. I also changed the model to model1002
I'm getting similar errors in run_default.
I setup the API Key and add all the packages so I am not seeing any problems from missing packages.

When I try to execute, the debugger stops in load_data.jl
at the following statement:

     if !isempty(empty_cols)
            error("Column(s) $(as_str[1:end-2]) have only NaNs and/or missings.")
        end

debugger hangs on this.
OK, turned off the debugger so processing code would go further.
Lots more errors.

WARNING: Method definition (::DSGE.var"#util#1596"{γ})(S) where {S<:Number} in module DSGE at C:\Users\bkrel\.julia\packages\DSGE\tJSkz\src\models\heterogeneous\two_asset_hank\helpers.jl:481 overwritten at C:\Users\bkrel\.julia\packages\DSGE\tJSkz\src\models\heterogeneous\two_asset_hank\helpers.jl:483.
Maybe thats a warning and is ignored, maybe not.

But, there's more:
ERROR: LoadError: Column(s) obs_longinflation, obs_longrate, obs_tfp, obs_nominalrate1, obs_nominalrate2, obs_nominalrate3, obs_nominalrate4, obs_nominalrate5, obs_nominalrate6 have only NaNs and/or missings.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] isvalid_data(m::Model1002{Float64}, df::DataFrame; cond_type::Symbol, check_empty_columns::Bool)
   @ DSGE C:\Users\bkrel\.julia\packages\DSGE\tJSkz\src\data\load_data.jl:423
 [3] load_data(m::Model1002{Float64}; cond_type::Symbol, try_disk::Bool, verbose::Symbol, check_empty_columns::Bool, summary_statistics::Symbol)
   @ DSGE C:\Users\bkrel\.julia\packages\DSGE\tJSkz\src\data\load_data.jl:90
 [4] estimate(m::Model1002{Float64}; verbose::Symbol, proposal_covariance::Matrix{Any}, mle::Bool, sampling::Bool, filestring_addl::Vector{String}, continue_intermediate::Bool, intermediate_stage_start::Int64, intermediate_stage_increment::Int64, save_intermediate::Bool, tempered_update_prior_weight::Float64, run_csminwel::Bool)
   @ DSGE C:\Users\bkrel\.julia\packages\DSGE\tJSkz\src\estimate\estimate.jl:82
 [5] estimate(m::Model1002{Float64})
   @ DSGE C:\Users\bkrel\.julia\packages\DSGE\tJSkz\src\estimate\estimate.jl:82
 [6] top-level scope
   @ e:\MonetaryTheory\NYFedPolicy\TestJulia\Test2.jl:14
in expression starting at e:\MonetaryTheory\NYFedPolicy\TestJulia\Test2.jl:14
The terminal process "C:\\Users\\bkrel\\AppData\\Local\\Programs\\Julia-1.7.3\\bin\\julia.exe '--color=yes', '--project=C:\Users\bkrel\.julia\environments\v1.7', 'e:\MonetaryTheory\NYFedPolicy\TestJulia\Test2.jl'" terminated with exit code: 1.

This all might be a consequence of no data, but I don't know.

Can anyone help straighten out this sample program?

Thanks.

Bruce

**Comment by MOAMaster** [comment]
I think I may have found the problem.
I compared run_default with the sample program.
You have to set check_empty_columns = false.
That should be in your sample program.
Is now doing the iterating, so will see if it gets through the whole application.

**Comment by ShlokG** [comment]
Hi Bruce,

Apologies for this issue and thank you for bringing it to our attention. It seems like we made a change to load_data but didn't re-run the examples to verify that they worked. We will be sure not to make this mistake in the future. We do plan on making a new release of the package soon which will have updated tests, examples, and documentation in addition to some new features.

Regards,
Shlok

**Comment by MOAMaster** [comment]
Thanks for letting me know.

When will I know that the revisions are ready?

 

I have a bunch of questions about programming the models.

I sent you an e-mail to your FRBNY address.


That may have gone into your spam folder.

Can you find and respond to me.

 

Thanks.

Bruce

 

From: ShlokG ***@***.*** ***@***.***> >
Date: June 2, 2022 at 11:29:26 AM PDT
To: "FRBNY-DSGE/DSGE.jl" ***@***.*** ***@***.***> >
Cc: MOAMaster ***@***.*** ***@***.***> >, Author ***@***.*** ***@***.***> >
Subject: Re: [FRBNY-DSGE/DSGE.jl] Can't Get Simple Example To Xqt (Issue #177)
Reply-To: "FRBNY-DSGE/DSGE.jl" ***@***.*** ***@***.***> >

﻿

Hi Bruce,

Apologies for this issue and thank you for bringing it to our attention. It seems like we made a change to load_data but didn't re-run the examples to verify that they worked. We will be sure not to make this mistake in the future. We do plan on making a new release of the package soon which will have updated tests, examples, and documentation in addition to some new features.

Regards,
Shlok
