### ISSUE TITLE
run_default.jl

### ISSUE THREAD

**Issue by freizue** [FRBNY-DSGE/DSGE.jl#182]
Hi everybody,

when I try to run the forecasting part of run_default.jl, I always get the following error:

forecast_one(m, :mode, :none, output_vars; check_empty_columns = false)  | Error: type DataType has no field mutable

I use Visual Studio Code on Windows and somehow my colleague running the same code on Linux can't reproduce the error.
Since I'm quite new to Julia and DSGE, I've only checked that the JLD2 package is up to date.
Perhaps someone could help me with the issue? Thank you in advance!

The exact error description with stacktrace is:

Argument 5 of 4 in call to forecast_one

ERROR: type DataType has no field mutable
Stacktrace:

getproperty at [.\Base.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

hasfielddata(T::Any) at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\data.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

#s61#23 at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\data.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

var"#s61#23"(T::Any, ::Any, #unused#::Any, initialized::Any) at [.\none](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

(::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any}) at [.\boot.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

odr at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\data.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

objodr at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\data.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

write_dataset at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\datasets.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

write(g::JLD2.Group{JLD2.JLDFile{IOStream}}, name::String, obj::Dict{Date, Int64}, wsession::JLD2.JLDWriteSession{Dict{UInt64, JLD2.RelOffset}}) at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\groups.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

write(f::JLD2.JLDFile{IOStream}, name::String, obj::Dict{Date, Int64}, wsession::JLD2.JLDWriteSession{Dict{UInt64, JLD2.RelOffset}}) at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\JLD2.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) (repeats 2 times)

write_forecast_metadata(m::Model1002{Float64}, file::JLD2.JLDFile{IOStream}, var::Symbol) at [C:\Users\Chiara.julia\packages\DSGE\tJSkz\src\forecast\io.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

(::DSGE.var"#1639#1642"{Model1002{Float64}, Symbol})(file::JLD2.JLDFile{IOStream}) at [C:\Users\Chiara.julia\packages\DSGE\tJSkz\src\forecast\io.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

jldopen(::DSGE.var"#1639#1642"{Model1002{Float64}, Symbol}, ::String, ::Vararg{Any}; kws::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}) at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\loadsave.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

jldopen at [C:\Users\Chiara.julia\packages\JLD2\4AJn8\src\loadsave.jl](vscode-file://vscode-app/c:/Users/Chiara/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)

**Comment by naivej** [comment]
the old JLD2 used in DSGE package is not compatible with julia 1.7 and above. 
using julia 1.6.7 (the current long term support version) should fix it
