### ISSUE TITLE
After 2020 Q3.

### ISSUE THREAD

**Issue by T-Shino-0603** [FRBNY-DSGE/DSGE.jl#208]
As for the DSGE program of FedNY on the web, it seems to require additional files or adjustment in the program after 2020 Q3. Indeed, the program on the web could not get an equilibrium and special shocks on consumption and labor supply are added in the paper. Can we share those updated programs?

**Comment by pranay-gundam** [comment]
Sorry for the very late attention, do you have any more specifics about the programs you are referring to?

**Comment by T-Shino-0603** [comment]
Thank you for your reply. I want the program used for "post Covid 19" estimation. Most recent program is preferable, but other programs which are used for estimation in 2022 or 2023 are also welcome. Thank you.

**Comment by pranay-gundam** [comment]
We are currently in the process of fixing some code and updating the codebase. It is hard to say a strict timeframe but do keep an eye on more pushes to this repo in the coming months.
