### ISSUE TITLE
Results mismatching: Different results of posterior for model parameters from Table 1 in the FRBNY DSGE published paper

### ISSUE THREAD

**Issue by yiminlily** [FRBNY-DSGE/DSGE.jl#21]
I'm trying to run the run_default.jl and get the forecasting results of FRBNY DSGE model as in [this paper](https://www.newyorkfed.org/research/staff_reports/sr647.html). The model's custom settings are set up as following:
`custom_settings = Dict{Symbol, Setting}(`
    `:data_vintage        => Setting(:data_vintage, "130412"),`
    `:date_forecast_start => Setting(:date_forecast_start, quartertodate("2013-Q2")),`
    `:use_population_forecast => Setting(:use_population_forecast, true),`
    `:n_anticipated_shocks => Setting(:n_anticipated_shocks, 6),`
    `:optimization_attempts => Setting(:optimization_attemps, 20),`
    `:date_presample_start => Setting(:date_presample_start, quartertodate("1984-Q1")))`
`m = Model990(custom_settings = custom_settings)`
The other properties are set up by default. I can load data and run estimate function successfully, but I'm getting totally different posterior results for parameters with running estimate(m) function.
For example, the posterior means that I get from mhsave_vint=130812.h5 file like following:

> alpha:0.1883, 

> S'':1.9619,

> h:0.3151,

but the posterior for model parameters read from paper are as below:

> alpha:0.351,

> S'':4.013,

> h:0.73.

I want to know if you have any updated paper for the latest code or there is some setting problem need to be fixed so that I can get the same results as published paper.

**Comment by xiaohaomao** [comment]
Dear Matthew and Cai @MattCocci   @caimichael @dseevr @musm 
**Same confusion as above. Got largely difference between  actual  julia result  of  posterior DSGE parameters  and posterior in the public paper (Table 1) with  data from 1984Q1 to 2013Q1.
**
is it reasonable? or any suggestions to fix this problem?

Best Regards
XiaoHao

**Comment by ethanmatlin** [comment]
Hello,
What data are you using? The package automatically loads all the FRED series, however there are a number of non-FRED series that we also use to estimate the model (Fernald TFP, long-term inflation expectations, OIS interest rate expectations, etc.) which are not all public. Are you sure you have all these series saved and are they being loaded in properly (you will receive warnings if some are missing)?

**Comment by yiminlily** [comment]
Hi ethanmatlin,
Thanks for your reply! I use data series that loaded from FRED by FRED API. For the non-FRED series, I use the saved historical data under "\DSGE.jl-master\test\reference\input_data" folder. All the data have been loaded in properly and there is only one warning as below.
`WARNING: /home/maoxiaohao201902/.julia/v0.4/DSGE/save/input_data/data/ois_130412.csv does not contain the entire date range specified; NaNs used.`
