### ISSUE TITLE
Installation on Julia 1.9.4

### ISSUE THREAD

**Issue by hadi-asfarangga** [FRBNY-DSGE/DSGE.jl#216]
I have the following error message when trying to install the DSGE package on Julia 1.9.4:
ERROR: Unsatisfiable requirements detected for package JLD2 [033835bb]:
 JLD2 [033835bb] log:
 ├─possible versions are: 0.1.0-0.4.38 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.4.38
 ├─restricted by julia compatibility requirements to versions: 0.4.28-0.4.38 or uninstalled, leaving only versions: 0.4.28-0.4.38
 └─restricted by compatibility requirements with DSGE [6cf23378] to versions: 0.1.0-0.3.3 — no versions left
   └─DSGE [6cf23378] log:
     ├─possible versions are: 0.5.0-1.3.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions: 0.5.0-1.3.0

I have tried to install JLD2 package with the version of 0.3.3, but got the following error message:
ERROR: Unsatisfiable requirements detected for package JLD2 [033835bb]:
 JLD2 [033835bb] log:
 ├─possible versions are: 0.1.0-0.4.38 or uninstalled
 ├─restricted to versions 0.3.3 by an explicit requirement, leaving only versions: 0.3.3
 └─restricted by julia compatibility requirements to versions: 0.4.28-0.4.38 or uninstalled — no versions left

How can I solve the installation issues? Thank you for your help.

**Comment by tavaresgarcia** [comment]
As mentioned in #182, the DSGE.jl package still works on Julia's current Long-term support (LTS) release: v1.6.7. You can download it from [here](https://julialang.org/downloads/#long_term_support_release). I've just installed and tested it today.
