### ISSUE TITLE
Failed installation on Julia 1.10

### ISSUE THREAD

**Issue by keigito** [FRBNY-DSGE/DSGE.jl#220]
The installation failed on julia ver. 1.10 with the error message showing:
Updating registry at `~/.julia/registries/General.toml`
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JLD2 [033835bb]:
 JLD2 [033835bb] log:
 ├─possible versions are: 0.1.0-0.4.45 or uninstalled
 ├─restricted by julia compatibility requirements to versions: 0.4.28-0.4.45 or uninstalled
 └─restricted by compatibility requirements with DSGE [6cf23378] to versions: 0.1.0-0.3.3 — no versions left
   └─DSGE [6cf23378] log:
     ├─possible versions are: 0.5.0-1.3.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions: 0.5.0-1.3.0

This seems to be related to the issue #216, which looks like it hasn't been addressed. Can someone take a look at this issue, please? Thanks!

**Comment by tavaresgarcia** [comment]
As mentioned in #216, the DSGE.jl package still works on Julia's current Long-term support (LTS) release: v1.6.7. You can download it from [here](https://julialang.org/downloads/#long_term_support_release).
