### ISSUE TITLE
estimate(m) and  no method matching fieldnames 

### ISSUE THREAD

**Issue by MarkoVito** [FRBNY-DSGE/DSGE.jl#24]
I am trying to run run_default.jl

After run  estimate(m) I get next error message

Creating dataset...
API key loaded.
Fetching FRED series GDP...
ERROR: MethodError: no method matching fieldnames(::HTTP.ExceptionRequest.StatusError)
Closest candidates are:
  fieldnames(::Core.TypeofBottom) at reflection.jl:175
  fieldnames(::Type{#s21} where #s21<:Tuple) at reflection.jl:177
  fieldnames(::DataType) at reflection.jl:172

Could you give me some advice in order to fix this?
I am using Julia Version 1.1.1 (2019-05-16)

**Comment by ethanmatlin** [comment]
Try using Julia 7 or 1.0. Unfortunately, we can't yet provide support for version 1.1. 

However, on the surface, this looks like it may be related to the HTTP, MbedTLS, or FredData packages. Maybe try googling the error and checking the versions of your packages?
