### ISSUE TITLE
MethodError while running the run_default.jl

### ISSUE THREAD

**Issue by jiamingkong** [FRBNY-DSGE/DSGE.jl#26]
Hi, I am trying to study this package, and I was running the 'run_default.jl'. It ran into this problem in the `estimate(m)` step:

```
MethodError: no method matching Optim.MultivariateOptimizationResults(::DSGE.Csminwel, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64, ::Float64, ::Bool, ::Float64, ::Float64, ::Bool, ::Float64, ::Float64, ::Bool, ::Array{Optim.OptimizationState{Float64,DSGE.Csminwel},1}, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  Optim.MultivariateOptimizationResults(::O, ::Tx, ::Tx, ::Tf, ::Int64, ::Bool, ::Bool, ::T, ::T, ::Tc, !Matched::Tc, !Matched::Bool, !Matched::T, ::T, !Matched::Tc, ::Tc, !Matched::Bool, !Matched::T, !Matched::Tc, !Matched::Bool, !Matched::M, !Matched::Int64, !Matched::Int64, !Matched::Int64, !Matched::Tls) where {O, T, Tx, Tc, Tf, M, Tls} at C:\Users\kinet\.julia\packages\Optim\hXam0\src\types.jl:167
```

The version I am using is listed below:
Julia: 1.0.4
  [6cf23378] DSGE v0.7.1
  [a93c6f00] DataFrames v0.19.1
  [7073ff75] IJulia v1.19.0
  [4d1e1d77] Nullables v0.0.8
  [bac558e1] OrderedCollections v1.1.0
  [ade2ca70] Dates
  [b77e0a4c] InteractiveUtils

How should I handle this error?

**Comment by chenwilliam77** [comment]
Hi jiaminkong,

1. We have not officially upgraded to Julia 1.0; we are still on Julia 0.7. We should be fully upgraded in the next few months.
2. Your error appears to us to be a package dependency issue. We replicated your error in Julia 1.0 and found that it didn't appear in Julia 0.7. It is likely that the method signature for MultivariateOptimizationResults in the Optim package has changed in an upgrade associated with Julia 1.0, so our tests are not currently catching it. 

Thank you for bringing this to our attention. After our release of the package in Julia 1.0, please let us know if you have any future problems.

Best,

William

**Comment by chenwilliam77** [comment]
Hi jiaminkong

Another thing you could try is check your Optim version. The tests for DSGE should work in Optim v0.16.0 when you're using Julia 1.0.

Best,

William

**Comment by jiamingkong** [comment]
Hi William, thank you for your reply. I can now successfully run the provided examples. What I did was pinning the version of Optim to 0.16.0 and it all worked out. Julia version is 1.0.
