### ISSUE TITLE
Tagging a patch

### ISSUE THREAD

**Issue by pkofod** [FRBNY-DSGE/DSGE.jl#7]
Thanks for merging #6. Unfortunately, Optim and DSGE cannot be at their latest tagged versions any more, as the last tag (0.1.3) is not compatible with Optim v0.6. So, just wanted to say that I think a lot of users would be happy with a patch tag. Of course, I don't know if "you're in the middle of something" and aren't ready to tag. Just a heads up !

**Comment by emoszkowski** [comment]
Done. Thanks for the heads up!
