### ISSUE TITLE
Julia Version (run_default.jl)

### ISSUE THREAD

**Issue by SanjayMoorjani** [FRBNY-DSGE/DSGE.jl#89]
Hi,

I've tried running the run_default.jl on different Julia versions but each of them is giving different errors. What version of Julia would you suggest?

### For Julia 1.0

**Error**

add DSGE
 Resolving package versions...
ERROR: Error when installing packages:
AssertionError: length(dirs) == 1
Stacktrace:
 [1] macro expansion at .\logging.jl:311 [inlined]
 [2] install_archive(::Array{String,1}, ::Base.SHA1, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:452
 [3] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:570 [inlined]
 [4] (::getfield(Pkg.Operations, Symbol("##21#24")){Pkg.Types.Context,Dict{Base.UUID,Base.SHA1},Dict{Base.UUID,Array{String,1}}})() at .\task.jl:259

### For Julia 0.7

ERROR: LoadError: UndefVarError: Model1002 not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include(::Module, ::String) at .\sysimg.jl:29
 [5] include(::String) at .\client.jl:398
 [6] top-level scope at none:0
in expression starting at C:\Users\moorj\AppData\Local\Julia-0.7.0\DSGE.jl-master\DSGE.jl-master\docs\examples\run_default.jl:16

### For Julia 1.1

ERROR: LoadError: FRED API Key not detected.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] load_fred_key() at /data/moorjani/.julia/packages/FredData/bGF0k/src/FredData.jl:82
 [3] Type at /data/moorjani/.julia/packages/FredData/bGF0k/src/FredData.jl:89 [inlined]
 [4] #load_fred_data#78(::Date, ::Date, ::Symbol, ::Function, ::Model1002{Float64}) at /data/moorjani/.julia/packages/DSGE/5LCnG/src/data/fred_data.jl:81
 [5] (::getfield(DSGE, Symbol("#kw##load_fred_data")))(::NamedTuple{(:start_date, :end_date, :verbose),Tuple{Date,Date,Symbol}}, ::typeof(load_fred_data), ::Model1002{Float64}) at ./none:0
 [6] #load_data_levels#61(::Symbol, ::Function, ::Model1002{Float64}) at /data/moorjani/.julia/packages/DSGE/5LCnG/src/data/load_data.jl:161
 [7] #load_data_levels at ./none:0 [inlined]
 [8] #load_data#60(::Symbol, ::Bool, ::Symbol, ::Bool, ::Symbol, ::Function, ::Model1002{Float64}) at /data/moorjani/.julia/packages/DSGE/5LCnG/src/data/load_data.jl:58
 [9] (::getfield(DSGE, Symbol("#kw##load_data")))(::NamedTuple{(:try_disk, :check_empty_columns, :summary_statistics),Tuple{Bool,Bool,Symbol}}, ::typeof(load_data), ::Model1002{Float64}) at ./none:0
 [10] top-level scope at /gsfs0/data/moorjani/DSGE-jl-master/docs/examples/run_default.jl:44
 [11] top-level scope at util.jl:156
 [12] include at ./boot.jl:326 [inlined]
 [13] include_relative(::Module, ::String) at ./loading.jl:1038
 [14] include(::Module, ::String) at ./sysimg.jl:29
 [15] include(::String) at ./client.jl:403
 [16] top-level scope at none:0
in expression starting at /gsfs0/data/moorjani/DSGE-jl-master/docs/examples/run_default.jl:43

### For Julia 1.3

ERROR: LoadError: MethodError: no method matching load_data(::Model1002{Float64}; try_disk=false, check_empty_columns=false, summary_statistics=:none)
Closest candidates are:
  load_data(::AbstractDSGEModel; cond_type, try_disk, verbose) at C:\Users\moorj\.julia\packages\DSGE\R18NA\src\data\load_data.jl:26 got unsupported keyword arguments "check_empty_columns", "summary_statistics"
Stacktrace:
 [1] kwerr(::NamedTuple{(:try_disk, :check_empty_columns, :summary_statistics),Tuple{Bool,Bool,Symbol}}, ::Function, ::Model1002{Float64}) at .\error.jl:125
 [2] (::DSGE.var"#kw##load_data")(::NamedTuple{(:try_disk, :check_empty_columns, :summary_statistics),Tuple{Bool,Bool,Symbol}}, ::typeof(load_data), ::Model1002{Float64}) at .\none:0
 [3] top-level scope at C:\Users\moorj\AppData\Local\Julia-1.3.1\DSGE.jl-master\DSGE.jl-master\docs\examples\run_default.jl:44
 [4] top-level scope at util.jl:155
 [5] include at .\boot.jl:328 [inlined]
 [6] include_relative(::Module, ::String) at .\loading.jl:1105
 [7] include(::Module, ::String) at .\Base.jl:31
 [8] include(::String) at .\client.jl:424
 [9] top-level scope at REPL[20]:1
in expression starting at C:\Users\moorj\AppData\Local\Julia-1.3.1\DSGE.jl-master\DSGE.jl-master\docs\examples\run_default.jl:43

I would really appreciate if there's a solution to resolve in any of the versions.

Thanks.

**Comment by chenwilliam77** [comment]
Hi Sanjay,

I would recommend using Julia 1.1, as that is the version we generally work in. The error you're getting is an indication that you haven't set up the FRED API key yet. I highly recommend going through the [documentation](https://frbny-dsge.github.io/DSGE.jl/latest/). For instructions specifically about the FRED API key, see [here](https://github.com/micahjsmith/FredData.jl/blob/master/README.md).

DSGE.jl is currently only supported in Julia 1.0-1.1. To use 0.7, you need to checkout a specific tag, per the instructions on the DSGE.jl README.

With regard to the Julia 1.0 error, it looks like there is some other error with installing packages, not with DSGE.jl in particular. I would try troubleshooting what that specific error actually means.

Best,

William

**Comment by SanjayMoorjani** [comment]
William,

Thanks for your reply. I'm using both 1.1.0 and 1.1.1 versions of Julia.

**While the Fred API key is sorted, I'm getting a new error on 1.1.0.**

ERROR: LoadError: UndefVarError: Model1002 not defined

I've tried to sort this out through (ERROR: UndefVarError: Model1002 not defined #29) but the solution doesn't seem to be working.

**For version 1.1.1** 

When I try to add the 'DSGE' package it runs for a while but then throws this error

....
Installed ChainRulesCore ────────────── v0.4.0
 Installed IniFile ───────────────────── v0.5.0
ERROR: Error when installing package DSGE:
AssertionError: length(dirs) == 1
Stacktrace:
 [1] install_archive(::Array{String,1}, ::Base.SHA1, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:482
 [2] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:596 [inlined]
 [3] (::getfield(Pkg.Operations, Symbol("##26#29")){Symbol,Pkg.Types.Context,Dict{Base.UUID,Base.SHA1},Dict{Base.UUID,Array{String,1}}})() at .\task.jl:259

While adding packages like ModelConstructors, Nullables, DataFrames, OrderedCollections, Dates have no issues, I get an error after a few files of DSGE package gets installed. Below is the entire error. If possible please let me know how to go about it.

Thanks.
....................................................................................................................................................


(v1.1) pkg> add DSGE
   Cloning default registries into `C:\Users\moorj\.julia`
   Cloning registry from "https://github.com/JuliaRegistries/General.git"
     Added registry `General` to `C:\Users\moorj\.julia\registries\General`
 Resolving package versions...
 Installed DataAPI ───────────────────── v1.3.0
 Installed ExponentialUtilities ──────── v1.6.0
 Installed PlotThemes ────────────────── v1.0.3
 Installed Plots ─────────────────────── v0.27.1
 Installed ForwardDiff ───────────────── v0.10.10
 Installed DiffEqBase ────────────────── v6.10.2
 Installed Missings ──────────────────── v0.4.3
 Installed PDMats ────────────────────── v0.9.12
 Installed DataValues ────────────────── v0.4.13
 Installed Libz ──────────────────────── v1.0.1
 Installed DataFrames ────────────────── v0.19.4
 Installed LibCURL ───────────────────── v0.5.2
 Installed OffsetArrays ──────────────── v1.0.4
 Installed OrderedCollections ────────── v1.2.0
 Installed IterativeSolvers ──────────── v0.8.4
 Installed Rmath ─────────────────────── v0.6.0
 Installed TranscodingStreams ────────── v0.9.5
 Installed DiffEqNoiseProcess ────────── v3.7.0
 Installed NearestNeighbors ──────────── v0.4.4
 Installed FredData ──────────────────── v0.4.0
 Installed GR ────────────────────────── v0.47.0
 Installed DiffRules ─────────────────── v1.0.1
 Installed DiffResults ───────────────── v1.0.2
 Installed SLEEFPirates ──────────────── v0.5.0
 Installed SteadyStateDiffEq ─────────── v1.5.1
 Installed Tables ────────────────────── v0.2.11
 Installed TreeViews ─────────────────── v0.3.0
 Installed DiffEqFinancial ───────────── v2.3.0
 Installed InvertedIndices ───────────── v1.0.0
 Installed NaNMath ───────────────────── v0.3.3
 Installed Compat ────────────────────── v2.2.0
 Installed AxisAlgorithms ────────────── v1.0.0
 Installed SparseDiffTools ───────────── v1.1.1
 Installed StaticArrays ──────────────── v0.12.3
 Installed Parameters ────────────────── v0.12.1
 Installed Observables ───────────────── v0.3.1
 Installed MbedTLS ───────────────────── v0.6.8
 Installed KernelDensity ─────────────── v0.5.1
 Installed VectorizationBase ─────────── v0.12.3
 Installed CMakeWrapper ──────────────── v0.2.4
 Installed JSON ──────────────────────── v0.21.0
 Installed PositiveFactorizations ────── v0.2.3
 Installed WeakRefStrings ────────────── v0.6.2
 Installed SpecialFunctions ──────────── v0.8.0
 Installed ColorTypes ────────────────── v0.9.1
 Installed Widgets ───────────────────── v0.6.2
 Installed MultiScaleArrays ──────────── v1.6.0
 Installed FillArrays ────────────────── v0.8.10
 Installed DiffEqJump ────────────────── v6.4.0
 Installed PooledArrays ──────────────── v0.5.3
 Installed Adapt ─────────────────────── v1.0.1
 Installed Optim ─────────────────────── v0.20.1
 Installed VersionParsing ────────────── v1.2.0
 Installed LightGraphs ───────────────── v1.3.3
 Installed StatsBase ─────────────────── v0.32.2
 Installed Ratios ────────────────────── v0.4.0
 Installed Conda ─────────────────────── v1.4.1
 Installed GenericSVD ────────────────── v0.2.2
 Installed Showoff ───────────────────── v0.3.1
 Installed HTTPClient ────────────────── v0.2.1
 Installed BinDeps ───────────────────── v1.0.1
 Installed Clustering ────────────────── v0.14.0
 Installed Distances ─────────────────── v0.8.2
 Installed CSV ───────────────────────── v0.5.23
 Installed StateSpaceRoutines ────────── v0.3.1
 Installed Interpolations ────────────── v0.12.10
 Installed ZygoteRules ───────────────── v0.2.0
 Installed MacroTools ────────────────── v0.5.5
 Installed Mocking ───────────────────── v0.7.1
 Installed Sundials ──────────────────── v3.8.3
 Installed PoissonRandom ─────────────── v0.4.0
 Installed Colors ────────────────────── v0.11.2
 Installed MuladdMacro ───────────────── v0.2.2
 Installed Parsers ───────────────────── v0.3.12
 Installed RandomNumbers ─────────────── v1.4.0
 Installed Inflate ───────────────────── v0.1.2
 Installed URIParser ─────────────────── v0.4.1
 Installed NLSolversBase ─────────────── v7.5.0
 Installed SMC ───────────────────────── v0.1.10
 Installed PlotUtils ─────────────────── v0.6.5
 Installed TimeZones ─────────────────── v0.11.0
 Installed BenchmarkTools ────────────── v0.4.3
 Installed FFMPEG ────────────────────── v0.2.4
 Installed ArrayInterface ────────────── v2.2.0
 Installed ArrayLayouts ──────────────── v0.1.5
 Installed NLsolve ───────────────────── v4.3.0
 Installed PackageCompiler ───────────── v0.6.5
 Installed Blosc ─────────────────────── v0.6.0
 Installed ClusterManagers ───────────── v0.3.2
 Installed IteratorInterfaceExtensions ─ v1.0.0
 Installed CpuId ─────────────────────── v0.2.2
 Installed Arpack ────────────────────── v0.3.2
 Installed LoopVectorization ─────────── v0.8.1
 Installed StatsFuns ─────────────────── v0.9.5
 Installed FilePathsBase ─────────────── v0.7.0
 Installed SimpleTraits ──────────────── v0.9.2
 Installed TableTraits ───────────────── v1.0.0
 Installed FileIO ────────────────────── v1.3.0
 Installed DimensionalPlotRecipes ────── v1.2.0
 Installed Contour ───────────────────── v0.5.3
 Installed CommonSubexpressions ──────── v0.2.0
 Installed LibExpat ──────────────────── v0.5.0
 Installed RecursiveArrayTools ───────── v1.2.1
 Installed CodecZlib ─────────────────── v0.6.0
 Installed JLD2 ──────────────────────── v0.1.13
 Installed LineSearches ──────────────── v7.0.1
 Installed DifferentialEquations ─────── v6.9.0
 Installed QuadGK ────────────────────── v2.3.1
 Installed BinaryProvider ────────────── v0.5.10
 Installed DocStringExtensions ───────── v0.8.1
 Installed Reexport ──────────────────── v0.2.0
 Installed UnPack ────────────────────── v1.0.1
 Installed GeometryTypes ─────────────── v0.8.3
 Installed WoodburyMatrices ──────────── v0.5.2
 Installed DiffEqDiffTools ───────────── v1.6.0
 Installed ExprTools ─────────────────── v0.1.1
 Installed ArnoldiMethod ─────────────── v0.0.4
 Installed BoundaryValueDiffEq ───────── v2.3.1
 Installed Nullables ─────────────────── v0.0.8
 Installed DiffEqPhysics ─────────────── v3.5.0
 Installed ResettableStacks ──────────── v1.0.0
 Installed NNlib ─────────────────────── v0.6.6
 Installed RecipesBase ───────────────── v0.7.0
 Installed DiffEqCallbacks ───────────── v2.10.0
 Installed StochasticDiffEq ──────────── v6.16.1
 Installed Requires ──────────────────── v1.0.1
 Installed CMake ─────────────────────── v1.2.0
 Installed Calculus ──────────────────── v0.5.1
 Installed DataValueInterfaces ───────── v1.0.0
 Installed HDF5 ──────────────────────── v0.12.5
 Installed DelayDiffEq ───────────────── v5.19.0
 Installed HTTP ──────────────────────── v0.8.15
 Installed SortingAlgorithms ─────────── v0.3.1
 Installed WinRPM ────────────────────── v0.4.3
 Installed Measures ──────────────────── v0.3.1
 Installed OrdinaryDiffEq ────────────── v5.26.8
 Installed BufferedStreams ───────────── v1.0.0
 Installed BandedMatrices ────────────── v0.14.3
 Installed StatsPlots ────────────────── v0.12.0
 Installed FFTW ──────────────────────── v1.1.0
 Installed CategoricalArrays ─────────── v0.7.7
 Installed Tracker ───────────────────── v0.2.6
 Installed VertexSafeGraphs ──────────── v0.1.2
 Installed Roots ─────────────────────── v0.8.4
 Installed MAT ───────────────────────── v0.7.0
 Installed FixedPointNumbers ─────────── v0.7.1
 Installed FunctionWrappers ──────────── v1.1.1
 Installed AbstractFFTs ──────────────── v0.5.0
 Installed DataStructures ────────────── v0.17.17
 Installed EzXML ─────────────────────── v1.0.0
 Installed SIMDPirates ───────────────── v0.8.4
 Installed Distributions ─────────────── v0.21.12
 Installed RecursiveFactorization ────── v0.1.2
 Installed ModelConstructors ─────────── v0.1.8
 Installed ChainRulesCore ────────────── v0.4.0
 Installed IniFile ───────────────────── v0.5.0
ERROR: Error when installing package DSGE:
AssertionError: length(dirs) == 1
Stacktrace:
 [1] install_archive(::Array{String,1}, ::Base.SHA1, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:482
 [2] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:596 [inlined]
 [3] (::getfield(Pkg.Operations, Symbol("##26#29")){Symbol,Pkg.Types.Context,Dict{Base.UUID,Base.SHA1},Dict{Base.UUID,Array{String,1}}})() at .\task.jl:259

**Comment by chenwilliam77** [comment]
Are you using Windows or MacOS/Linux?

**Comment by chenwilliam77** [comment]
Looks like this is the same error, and it doesn't look like they've figured it out either.
https://github.com/JuliaLang/Pkg.jl/issues/1116

**Comment by SanjayMoorjani** [comment]
William,

Thanks again for your reply. I'm using Julia 1.1.0 on a Linux cluster which gives me the following error:

ERROR: LoadError: UndefVarError: Model1002 not defined

**Comment by chenwilliam77** [comment]
Could you uninstall DSGE and reinstall it? Please make sure to install DSGE at v1.1.15. Also, are you just running 

```
include("run_default.jl")
```

in the Julia REPL?

**Comment by SanjayMoorjani** [comment]
William,

The code is running now. DSGE v1.1.15 was still giving some issues but it's working fine for DSGE v1.1.5. It keeps installing DSGE 0.8.1 even after deleting it and reinstalling DSGE package or using 'up' to upgrade it. This is because of the previous versions of some preinstalled dependencies of DSGE which were restricting the version to 0.8.1.

One last thing, how much time does it take on average for run_default.jl to run on a Linux system in your experience.

While it's still giving issues on Windows, it works fine on Linux with Julia 1.1.0 and DSGE v1.1.5. 

Thanks again for your reply.

**Comment by chenwilliam77** [comment]
run_default.jl should take roughly 30 minutes.
