### ISSUE TITLE
Compatibility with more recent Julia versions

### ISSUE THREAD

**Issue by wupeifan** [FRBNY-DSGE/DSGE.jl#98]
It seems that the compatibility is restricted to Julia 1.0 and 1.1. It would be great if you guys can allow more recent versions (currently 1.4 is the state-of-the-art) of Julia.

**Comment by chenwilliam77** [comment]
Hi Peifan,

Thanks for your interest! We have tested the package in Julia 1.3, and it works, so if you'd like to immediately start working with the package in higher Julia versions, I'd recommend dev'ing the package yourself and changing the restriction in the Project.toml file. Currently, we are in the progress of finishing up some significant additions to DSGE.jl, so we plan on increasing the version compatibility with the next planned release (v1.6). We expect the new release to occur with the next month or so.

Best,

William

**Comment by wupeifan** [comment]
Cool, thanks for your prompt update. I just want to avoid editing the toml file myself and that's why I asked. I think it actually makes sense to support Julia >=1.0: Julia is rigorously following semantic versioning.

**Comment by chenwilliam77** [comment]
Hi Peifan,

That is fair, and I think we might do that in the next release. My minor hesitance rests in the fact that it takes time for us to get the most recent stable Julia release, so we aren't always able to test in that release. Debugging by sending jobs to Travis would be a painful process. On the other hand, in contrast to Julia 0.7, the differences among the various Julia 1 versions seem fairly minor.

Best,

William

**Comment by chenwilliam77** [comment]
@wupeifan I am just letting you know that DSGE.jl at v1.1.6 should be compatible with all Julia 1.x versions
